let array4 = [];
let u1 = array4.unshift("a");
console.log(u1);
console.log(array4);
let u2 = array4.unshift("b");
console.log(u2);
console.log(array4);
let s1 = array4.shift();
console.log(s1);
console.log(array4);
let s2 = array4.shift();
console.log(s2);
console.log(array4);